# Generated by Django 4.1.6 on 2023-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='clients_logos')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('full_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 480 X 380 pixels')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 480 X 380 pixels')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, default=0, null=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience_section_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 480 X 380 pixels')),
            ],
        ),
        migrations.CreateModel(
            name='Home_page_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_page_carousel_images', verbose_name='Recommended image resulation is 1440 X 680 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('short_brief', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 480 X 380 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_card_images', verbose_name='Recommended image resulation is 480 X 380 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
