# Generated by Django 4.1.6 on 2023-02-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_about_page_mission_about_page_vision_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_page_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 1440 X 380 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_page_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 1440 X 380 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_page_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common_pictures', verbose_name='Recommended image resulation is 1440 X 380 pixels')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
