# Generated by Django 4.1.6 on 2023-02-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about_page_banner_contact_page_banner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience_image',
            new_name='Why_us_image',
        ),
        migrations.RenameModel(
            old_name='Experience_section_heading',
            new_name='Why_us_section_heading',
        ),
        migrations.RenameModel(
            old_name='Experience_points',
            new_name='WhyUs_points',
        ),
    ]
