# Generated by Django 4.1.6 on 2023-02-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_experience_image_why_us_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_page_banner',
            new_name='AboutPageBanner',
        ),
        migrations.RenameModel(
            old_name='About_page_mission',
            new_name='AboutPageMission',
        ),
        migrations.RenameModel(
            old_name='About_page_vision',
            new_name='AboutPageVision',
        ),
        migrations.RenameModel(
            old_name='Service_page_banner',
            new_name='ContactPageBanner',
        ),
        migrations.RenameModel(
            old_name='Home_page_carousel',
            new_name='HomePageCarousel',
        ),
        migrations.RenameModel(
            old_name='Service_card',
            new_name='ServiceCard',
        ),
        migrations.RenameModel(
            old_name='About_page_banner',
            new_name='ServicePageBanner',
        ),
        migrations.RenameModel(
            old_name='Why_us_image',
            new_name='WhyUsImage',
        ),
        migrations.RenameModel(
            old_name='WhyUs_points',
            new_name='WhyUsPoints',
        ),
        migrations.RenameModel(
            old_name='Why_us_section_heading',
            new_name='WhyUsSectionHeading',
        ),
    ]
