# Generated by Django 4.1.6 on 2023-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contact_page_banner_aboutpagebanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='logo',
            field=models.FileField(upload_to='clients_logos'),
        ),
    ]
